version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "4000:27017"

  nodejs:
    image: yashcse21/devops:backend
    container_name: nodejs
    environment:
      - DB=mongodb://mongodb:27017
      - SECRET=mysecretisthis
    ports:
      - "8021:8080"
    depends_on:
      - mongodb
      - knn
      - gen_ai

  knn:
    image: yashcse21/devops:knn
    container_name: knn
    ports:
      - "3005:3000"

  gen_ai:
    image: yashcse21/devops:gen_ai
    container_name: gen_ai
    ports:
      - "8005:8000"
