version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "4000:27017"

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs
    environment:
      - DB=mongodb://mongodb:27017
      - SECRET=mysecretisthis
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
