version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "4000:27017"

  nodejs:
    image: yashcse21/major10:node_app
    container_name: nodejs
    environment:
      - DB=mongodb://mongodb:27017
      - SECRET=mysecretisthis
    ports:
      - "8021:8080"
    depends_on:
      - mongodb
      - knn
      - gen_ai

  knn:
    image: yashcse21/major10:knn
    container_name: knn
    ports:
      - "3000:3000"

  gen_ai:
    image: yashcse21/major10:gen_ai2
    container_name: gen_ai
    ports:
      - "8000:8000"
