apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: yashcse21/major1:node_app
        ports:
        - containerPort: 8080
        env:
        - name: DB
          value: "mongodb://mongodb:27017"
        - name: SECRET
          value: "mysecretisthis"
      initContainers:
      - name: wait-for-mongodb
        image: busybox
        command: ['sh', '-c', 'until nc -z mongodb 27017; do echo waiting for mongodb; sleep 2; done;']
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  selector:
    app: nodejs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: knn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knn
  template:
    metadata:
      labels:
        app: knn
    spec:
      containers:
      - name: knn
        image: yashcse21/major1:knn
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: knn
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30030
  selector:
    app: knn
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nodejs-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodejs
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: knn-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: knn
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
