apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs
          image: yashcse21/major10:node_app1
          env:
            - name: DB
              value: "mongodb://mongodb:27017"
            - name: SECRET
              value: "mysecretisthis"
          ports:
            - containerPort: 8080
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30221
  selector:
    app: nodejs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: knn
spec:
  replicas: 2
  selector:
    matchLabels:
      app: knn
  template:
    metadata:
      labels:
        app: knn
    spec:
      containers:
        - name: knn
          image: yashcse21/major10:knn
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: knn
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30300
  selector:
    app: knn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gen-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gen-ai
  template:
    metadata:
      labels:
        app: gen-ai
    spec:
      containers:
        - name: gen-ai
          image: yashcse21/major10:gen_ai
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: gen-ai
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30800
  selector:
    app: gen-ai
